# .bash_profile

# set LANG to en_US.UTF-8
export LANG="en_US.UTF-8"

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs
export PATH=$PATH:$HOME/.local/bin:$HOME/bin
