# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# set the tty for gpg to use
export GPG_TTY="$(tty)"
# use gpg-agent for ssh
export SSH_AUTH_SOCK="$HOME/.gnupg/S.gpg-agent.ssh"

# phat colors yo
export TERM="screen-256color"

# use vim
export EDITOR="vim"

# allow powerline to report back to tmux
powerline-daemon -q
source /usr/share/powerline/bash/powerline.sh
